CatalystInspection/Models/CatalystDetailViewModel.cs
using API.Core.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CatalystInspection.Models
{
    public class CatalystDetailViewModel
    {
        public CatalystDetailViewModel()
        {
            catINFO = new List<catalystINFO>();
        }
        
        public string datefrom { get; set; }
        public string dateto { get; set; }
        public IEnumerable<catalystINFO> catINFO { get; set; }

    }
}

CatalystInspection/Models/CatalystImgViewModel.cs
using API.Core.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CatalystInspection.Models
{
    public class CatalystImgViewModel
    {
        public CatalystImgViewModel()
        {
            imgoverlap = new List<catalystdetail>();
            imgsurtop = new List<catalystdetail>();
            imgsurside = new List<catalystdetail>();
        }
        public IEnumerable<catalystdetail> imgoverlap { get; set; }
        public IEnumerable<catalystdetail> imgsurtop { get; set; }
        public IEnumerable<catalystdetail> imgsurside { get; set; }
    }
}

CatalystInspection/Models/ErrorViewModel.cs
using System;

namespace CatalystInspection.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CatalystInspection/Models/RestCatalystViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CatalystInspection.Models
{
    public class RestCatalystViewModel
    {
        public string uid { get; set; }
        public string defect_type { get; set; }
        public string imagebase64 { get; set; }
        public string image_name { get; set; }
        public DateTime date_input { get; set; }
    }
}

CatalystInspection/Controllers/CatalystController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using API.Core.Entity;
using API.Core.Interface;
using ImageMagick;
using System.IO;
using CatalystInspection.Models;

namespace CatalystInspection.Controllers
{
    public class CatalystController : Controller
    {
        public readonly ICatalystServieces _Catalyst;
        public CatalystController(ICatalystServieces catalyst)
        {
            _Catalyst = catalyst;
        }
        public IActionResult Index(CatalystDetailViewModel dv)
        {

            string path = @"wwwroot";
            string fullPath;
            string current;

            fullPath = Path.GetFullPath(path);
            current = Directory.GetCurrentDirectory();
            string pathSave = $"wwwroot{"/images/imgcatalyst/"}";
            var path_ = Path.Combine(Directory.GetCurrentDirectory(), pathSave, "aa" + ".png");
            IEnumerable<catalystINFO> cInfo = new List<catalystINFO>();
            //ViewData["datefrom"] = DateTime.Now.ToString("dd/MM/yyyy");
            //ViewData["dateto"] = DateTime.Now.ToString("dd/MM/yyyy");
            var tmp = _Catalyst.GetCatalystINFO();
            var res = tmp.Select(o => new catalystINFO { 
                date_input = DateTime.Parse(o.date_input.ToString())
            });
            
            if (!String.IsNullOrEmpty(dv.datefrom) && !String.IsNullOrEmpty(dv.dateto))
            {
                DateTime dateF = DateTime.Parse(dv.datefrom + " 0:00:00");
                DateTime dateT = DateTime.Parse(dv.dateto + " 23:59:59");
                cInfo = tmp.Where(o => DateTime.Parse(o.date_input.ToString()) >= dateF && DateTime.Parse(o.date_input.ToString()) <= dateT);
            }
            else
            {
                cInfo = tmp;
            }

            //var d = tmp.Select(o => new { a = o.overlap.ToString() });
            CatalystDetailViewModel catalystView = new CatalystDetailViewModel();
            catalystView.catINFO = cInfo;
            
            return View(catalystView);
        }
        public async Task<IActionResult> DetailInfo(string uid)
        {
            CatalystImgViewModel cImg = new CatalystImgViewModel();
            var tmp = await _Catalyst.GetCatalydtDetailByID(uid);
            var resoverlap = tmp.Where(o => o.defect_type == "0").ToList();
            var ressurtop = tmp.Where(o => o.defect_type == "1").ToList();
            var ressurside = tmp.Where(o => o.defect_type == "2").ToList();
            cImg.imgoverlap = resoverlap;
            cImg.imgsurtop = ressurtop;
            cImg.imgsurside = ressurside;
            return View(cImg);
        }
        
        [HttpGet]
        public async Task<IActionResult> NewCatalyst(string timestamp)
        {
            try
            {
                catalyst cl = new catalyst();
                cl.date_input = Convert.ToDateTime(DateTime.Now.ToString());
                cl.timestamp = timestamp;
                await _Catalyst.Addcatalyst(cl);
                return Ok();
            }catch(Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
        [HttpPost]
        public async Task<IActionResult> NewCatalystDetail([FromBody]RestCatalystViewModel restdata)
        {
            try
            {
                SaveimageBase64(restdata.imagebase64, restdata.defect_type +"_"+ restdata.image_name, 416, 416);
                catalystdetail cd = new catalystdetail();
                cd.uid = restdata.uid;
                cd.defect_type = restdata.defect_type;
                cd.image = restdata.defect_type + "_" + restdata.image_name;
                cd.date_input = Convert.ToDateTime(DateTime.Now.ToString());
                await _Catalyst.AddDetailCatalyst(cd);
                return Ok();
            }catch(Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

       
        public void SaveimageBase64(string data,string filename, int maxWidth, int maxHeight)
        {
            try
            {
                var bytes = Convert.FromBase64String(data);
                var image = new MagickImage(bytes);
                string pathSave = $"wwwroot{"/images/imgcatalyst/"}";
                var path_ = Path.Combine(Directory.GetCurrentDirectory(), pathSave, filename+".png");
                var size = new MagickGeometry(maxWidth, maxHeight);
                image.Resize(size);
                image.Write(path_);
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                Console.WriteLine("Message Error on method SaveimageBase64 " + error);
            }
        }

        
    }
}

CatalystInspection/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CatalystInspection.Models;

namespace CatalystInspection.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CatalystInspection/Views/Catalyst/DetailInfo.cshtml
@model CatalystInspection.Models.CatalystImgViewModel
@{
    ViewData["Title"] = "DetailInfo";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                Detail
            </div>
            <div class="card-body">
                <div class="card">
                    <div class="card-header text-center">
                        Overlap
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model.imgoverlap)
                            {
                                string ov = item.image.ToString() + ".png";
                                <div class="col-sm-2 mt-2">
                                    <img style="width:100%" src="~/images/imgcatalyst/@ov" />
                                </div>
                            }
                            @if (Model.imgoverlap.ToArray().Length < 1)
                            {
                                <div class="col-sm-2 mt-2">
                                    Not have defect
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header text-center">
                        Surfacetop
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model.imgsurtop)
                            {
                                string st = item.image.ToString() + ".png";
                                <div class="col-sm-2 mt-2">
                                    <img style="width:100%" src="~/images/imgcatalyst/@st" />
                                </div>
                            }
                            @if (Model.imgsurtop.ToArray().Length < 1)
                            {
                                <div class="col-sm-2 mt-2">
                                    Not have defect 
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        Surfaceside
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model.imgsurside)
                            {
                                string ss = item.image.ToString() + ".png";
                                <div class="col-sm-2 mt-2">
                                    <img style="width:100%" src="~/images/imgcatalyst/@ss" />
                                </div>
                            }
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

CatalystInspection/Views/Catalyst/Index.cshtml
@model CatalystInspection.Models.CatalystDetailViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                Catalyst
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <form asp-controller="Catalyst" asp-action="Index" method="get">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="input-group input-group-sm mb-2">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroup-sizing-sm-f">Date :</span>
                                                </div>
                                                <input id="datefrom" asp-for="datefrom" type="text" class="form-control" aria-label="Small" autocomplete="off" aria-describedby="inputGroup-sizing-sm-f">

                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="input-group input-group-sm mb-2">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroup-sizing-sm-t">To :</span>
                                                </div>
                                                <input id="dateto" asp-for="dateto" type="text" class="form-control" aria-label="Small" autocomplete="off" aria-describedby="inputGroup-sizing-sm-t">
                                            </div>
                                          
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-1">

                                </div>
                                <div class="col-sm-2">
                                    @*<input class="btn btn-outline-primary btn-sm" type="button" value="Serach" />*@
                                    <button class="btn btn-outline-primary btn-sm" type="submit" onclick="a()">Serach</button>
                                </div>
                            </div>
                           

                        </form>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table id="tablecatalyst" class="table table-striped table-bordered second" style="width:100%">
                                <thead>
                                    <tr class="text-center">
                                        <th>ID</th>
                                        <th>Overlap</th>
                                        <th>Surfacetop</th>
                                        <th>Surfaceside</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.catINFO)
                                    {
                                        <tr>
                                            <td style="cursor:pointer">
                                                <a asp-action="Detailinfo" asp-route-uid="@item.uid">@item.uid</a>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(mitem => item.overlap)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(mitem => item.surfacetop)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(mitem => item.surfaceside)
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>




@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script>
        $(document).ready(function () {
            $('#datefrom').datetimepicker({
                timepicker: true,
                format: 'd/m/Y',
                defaultDate: new Date()
            });
            $('#dateto').datetimepicker({
                timepicker: false,
                format: 'd/m/Y',
                defaultDate: new Date()
            });
      
        });
        
        //$(function () {
        //    $('#datefrom').datetimepicker({
        //        timepicker: true,
        //        format: 'd/m/Y',
        //        defaultDate: new Date()
        //    });
        //    $('#dateto').datetimepicker({
        //        timepicker: false,
        //        format: 'd/m/Y'
        //    });
        //});
        var a = function () {
            var from = $('#datefrom').val();
            //alert(from);
        }
    </script>
}

CatalystInspection/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CatalystInspection/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CatalystInspection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CatalystInspection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatalystInspection</title>
    
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CatalystInspection</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2563 - CatalystInspection</p>
        </footer>
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datetimepicker/jquery.js"></script>
    <script src="~/datetimepicker/jquery.datetimepicker.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CatalystInspection/Views/Shared/_Layout1.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="~/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/libs/css/style.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/fontawesome/css/fontawesome-all.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/chartist-bundle/chartist.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/morris-bundle/morris.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/c3charts/c3.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/flag-icon-css/flag-icon.min.css">
    <link href="~/datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/vendor/datatables/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="~/assets/vendor/datatables/css/buttons.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="~/assets/vendor/datatables/css/select.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="~/assets/vendor/datatables/css/fixedHeader.bootstrap4.css">

    <title>Concept - Bootstrap 4 Admin Dashboard Template</title>





</head>

<body>
    <div class="dashboard-main-wrapper">
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                <a class="navbar-brand" href="index.html">
                    <img src="~/images/attglogo.png" height="50" style="padding-left:40px" />
                </a>
            </nav>
        </div>
        <div class="container content-wrapper pt-3">
            @RenderBody()
        </div>
        @*<div class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <a href="https://colorlib.com/wp/">Colorlib</a>.
                        </div>
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="text-md-right footer-links d-none d-sm-block">
                                <a href="javascript: void(0);">About</a>
                                <a href="javascript: void(0);">Support</a>
                                <a href="javascript: void(0);">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>*@
    </div>
    <script src="~/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!-- bootstap bundle js -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="~/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <script src="~/assets/vendor/multi-select/js/jquery.multi-select.js"></script>
    <!-- main js -->
    <script src="~/assets/libs/js/main-js.js"></script>
    <!-- chart chartist js -->
    <script src="~/assets/vendor/charts/chartist-bundle/chartist.min.js"></script>
    <!-- sparkline js -->
    <script src="~/assets/vendor/charts/sparkline/jquery.sparkline.js"></script>
    <!-- morris js -->
    <script src="~/assets/vendor/charts/morris-bundle/raphael.min.js"></script>
    <script src="~/assets/vendor/charts/morris-bundle/morris.js"></script>
    <!-- chart c3 js -->
    <script src="~/assets/vendor/charts/c3charts/c3.min.js"></script>
    <script src="~/assets/vendor/charts/c3charts/d3-5.4.0.min.js"></script>
    <script src="~/assets/vendor/charts/c3charts/C3chartjs.js"></script>
    <script src="~/assets/libs/js/dashboard-ecommerce.js"></script>

    <!-- Canvasjs -->
    <script src="~/assets/script/jquery.canvasjs.min.js"></script>

    <!--Datetime-->
    <script src="~/datetimepicker/jquery.js"></script>
    <script src="~/datetimepicker/jquery.datetimepicker.js"></script>
    <!--Datatable-->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/vendor/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="~/assets/vendor/datatables/js/buttons.bootstrap4.min.js"></script>
    <script src="~/assets/vendor/datatables/js/data-table.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.0.4/js/dataTables.rowGroup.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>

</html>